### ISSUE TITLE
Implement the user update logic

### ISSUE THREAD

**Issue by pamodaaw** [wso2-extensions/identity-office365#4]
**Description:**
The provisioned user updating logic which is triggered by the provisioning operation UPDATE is not implemented.[1]

[1] [https://github.com/wso2-extensions/identity-office365/blob/master/components/org.wso2.carbon.identity.outbound.provisioning.connector.office365/src/main/java/org/wso2/carbon/identity/outbound/provisioning/connector/office365/Office365ProvisioningConnector.java#L180](https://github.com/wso2-extensions/identity-office365/blob/master/components/org.wso2.carbon.identity.outbound.provisioning.connector.office365/src/main/java/org/wso2/carbon/identity/outbound/provisioning/connector/office365/Office365ProvisioningConnector.java#L180)

**Suggested Labels:**
Improvement

**Comment by darshanasbg** [comment]
Let's move this to product-is

**Comment by svenzimmermann** [comment]
Any news with update logic? We urgently need the function to update the changed departments in Azure when the WSO2 roles are changed. If it is helpful, we would like to support the development.

We have hundreds of students here who change groups regularly. Deleting them from the Office 365 role and azure each time and then provisioning them new with correct groups is a nightmare.

**Comment by pamodaaw** [comment]
We are going to implement the update functionality for the provisioned users in the Azure AD. We will follow the following approach for implementing the functionality. 
1. Once the user profile of the users in the WSO2 Identity Server is updated, the provisioning connector will be triggered.
2. The provisioning connector retrieves the attributes of the provisioning entity.
3. The provisioning connector calls the user attribute [update endpoint of the Microsoft Graph API](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http),`PATCH /users/{id|userPrincipalName}`. User id can be taken from the identifier of the provisioning entity.
4. Upon the successful update of the user properties in the Azure AD, the API will respond with the response code 204 - No content.
5. The provisioning connector will not update the password of the provisioned user.

Once the implementation is complemented, the flow will be as follows.

1. When the user attributes that are already provisioned are updated in the WSO2 IS, they will be automatically synced to the Azure AD.
2. If dynamic membership rules have been defined, the groups that the user belongs to will be updated accroding to the rule.

Please let us know if you have any concerns regarding this approach.

**Comment by svenzimmermann** [comment]
I am happy to hear, that you implement the update logic for Azure. The described functionality would be a great improvement to the connector.

A question about your approach:

Is the provisioning connector triggered when the role in an LDAP user store is changed?
I ask because in our usage scenario the attribute changes are usually changed on the connected on premise LDAP server. I want to make sure that the planned trigger works in that case.

**Comment by pamodaaw** [comment]
According to the provisioning framework of the WSO2 identity server, any user attribute change or role change will trigger the provisioning connector. The Office365ProvisioningConnector is written specifically to perform the provisioning tasks when the user attributes are changed.

If the LDAP userstore is directly updated without using the Identity Server, the provisioning framework will not be triggered. So that the provisioning connector is not invoked. If you need the changes to be synced to the Azure, you will have to update the userstore via the WSO2 IS.

**Comment by svenzimmermann** [comment]
In the education area in germany, students are provided via special on premise school administration server solutions. The maintenance of user data via WSO2 is therefore only intended to supplement optional entries. The mandatory data such as roles classes, project groups etc. come from the LDAP user store without WSO2 interaction.
If at least updates of user roles are not invoking the provisioning connector, this is a real security problem. We need a solution for this behavior ...

Is there no option that the connector can listen to role related events in the ldap user store?
I understood you that way in your article on https://medium.com/identity-beyond-borders/writing-an-outbound-provisioning-connector-4a3450d0e7a2 .

As a workaround, is there a possibility to trigger the provisioning framework or the connector of WSO2 IS with a CLI command, a cronjob or scheduling? So e.g. all users are at least synced once at night ...

**Comment by pamodaaw** [comment]
It's not a good practice to change the storage when you are using a centralized IAM system. It can cause issues like this where the required changes are not properly synced among the nodes of the system and also if all the related data is not properly updated, the data may get corrupted. The correct way is to govern the data via the central system so that the changes are reflected at all the other components of the system as well. 

In your use-case, if you have any limitation in managing the storage via the WSO2 Identity Server all the time, you may have to write an external client for triggering the provisioning connector periodically. From the external client, you can do a redundant user profile update by calling the SCIM patch endpoint periodically for all the users or for the users you want. When the user profile gets updated, the provisioning connector will be triggered and the changes will be synced to Azure

**Comment by svenzimmermann** [comment]
How much effort would it be for a developer to program such a small client application. The client application should only trigger the update of all users of certain roles via comand line. 
For the community, such a client would certainly be a useful extension. I don't think my use case is that exotic.

Do you know someone who could be interested and has the necessary knowledge?

**Comment by pamodaaw** [comment]
If you have the list of users and the list of attributes that have been updated, you can call the SCIM API from the client application to do a redundant update. You may refer to the WSO2 SCIM 2.0 API documentation to check on the required APIs. (https://is.docs.wso2.com/en/5.10.0/develop/scim2-rest-apis/). Once these are identified, the basic programming knowledge would be enough to implement the client application by calling the APIs.

**Comment by svenzimmermann** [comment]
Thanks for your answer. I am changing now one attribute of each user with:
curl -v -k --user [username]:[password] -X PATCH -d '{"schemas":[],"Operations":[{"op":[operation],"value":{[attributeName]:[attribute value]}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/[user ID]

Am I getting you right? If I change any attribute of a user via scim, would all attributes of this user in Azure be updated?

**Comment by pamodaaw** [comment]
A new Office365 Provisioning Connector version is released with the capability to update the supported user attributes in the Azure AD when the corresponding attributes are changed in the WSO2 Identity Server. You may download the new connector from the [IS Connector Store](https://store.wso2.com/store/assets/isconnector/details/5b67b248-fa00-4178-bf16-5606876ace4b)

If you have more questions please feel free to create an issue in [product-is repository](https://github.com/wso2/product-is/issues/new/choose)[2]

[1] https://store.wso2.com/store/assets/isconnector/details/5b67b248-fa00-4178-bf16-5606876ace4b
[2] https://github.com/wso2/product-is/issues/new/choose

**Comment by pamodaaw** [comment]
@svenzimmermann Not all the attributes are synced. We support the basic set of attributes that are mandatory to create a user in the Azure AD side. [1]

[1] https://github.com/wso2-extensions/identity-office365/blob/master/components/org.wso2.carbon.identity.outbound.provisioning.connector.office365/src/main/java/org/wso2/carbon/identity/outbound/provisioning/connector/office365/Office365ProvisioningConnector.java#L427
